#11
IvanPiri/RealEstateManager pull request #12
Opened 2020-12-09 15:03 UTC by Vvarbanov

[add] building info crud operations and basic views

[add] estate details view including building info

2020-12-10 18:59 UTC, IvanPiri requested changes
Имаш няколко дреболии за оправяне (нищо сериозно, повечето неща са от гледна точка на coding style и добри практики с ASP.NET MVC). Останалото Looks Good To Me.

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Controllers/EstateController.cs
> +                if (model.Type.Equals(EstateType.Apartment) || model.Type.Equals(EstateType.House))
Тук можеш просто да използваш:
```cs
if (model.Type == EstateType.Apartment || model.Type == EstateType.House)
```
В C# препоръчаната проверка за стойност на enum става или със `switch` или с оператор `==`.

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Content/Site.scss
> +.jumbotron {
Добре е да не override-ваме класове. Обикновено използваме `!important`, за да оправим друг `!important`. Тук можеш да добавиш нов клас и в HTML-a също.

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Controllers/EstateController.cs
> +                if (model.Type.Equals(EstateType.Apartment) || model.Type.Equals(EstateType.House))
Виж горния коментар за сравняването на enum стойности в C#.

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Controllers/EstateController.cs
> +                if (model.Type.Equals(EstateType.Land) && model.BuildingInfoId.HasValue)
Виж горния коментар за сравняването на enum стойности в C#.

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Models/Estate/EstateGetModel.cs
> +                } :
```cs
return x != null
    ? a
    : b; // (Pseudocode)
```

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Repository/Sets/BuildingInfoSet.cs
> +            var estate = _databaseContext.Estates.Where(x => x.Id == data.EstateId).FirstOrDefault();
```cs
var estate = _databaseContext.Estates
    .FirstOrDefault(x => x.Id == data.EstateId);
```

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Views/BuildingInfo/Details.cshtml
> +        @Localization.GetString("BuildingInfoIndexPage_InfoFloors") @Model.Floors
Тук (и на други места където искаш само да показваш данни) правилното нещо е:
```cs
@Html.LabelFor(x => x.Floors)
@Html.DisplayFor(x => x.Floors)
```

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Views/BuildingInfo/Details.cshtml
> +}
Удачно ли ще е да имаме бутон към имота тук? Или бутон за редактиране на самото BuildingInfo ? Ако мислиш, че да, ще трябва в модела ти да се появят съответнити `Guid`-ове. Оставям този въпрос на твоя преценка.

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Views/Estate/Details.cshtml
> +                @Localization.GetString("EstateIndexPage_EstateArea") @Model.Area @Localization.GetString("EstateIndexPage_AreaSign")
Отново `LabelFor` и `DisplayFor`. За enum-ите и bool полетата ще ни трябва специален DisplayTemplate преди да може да се показват с `DisplayFor` (това е за друго issue).

2020-12-10 18:59 UTC, IvanPiri commented on src/RealEstateManager/Models/Estate/EstateGetModel.cs
> +        public BuildingInfoGetModel getBuildingInfoModel()
Методите започват с главна буква.

2020-12-11 08:52 UTC, Vvarbanov commented on src/RealEstateManager/Views/BuildingInfo/Details.cshtml
> +}
Не мисля че е удачно да имаме бутон за имота тук, в момента се ползва само за partial view и вече го има на страницата за детайли на имота. Но добавих бутони за редактиране и изтриване на имот и детайли в страницата за детайли на имота.

2020-12-11 11:01 UTC, IvanPiri approved these changes
С последните промени looks good to me.

2020-12-11 11:02 UTC, merged